project:
  type: book

book:
  title: "Introduction à la gestion des données"
  author: "Félix Marchais"
  date: "2026-01-06"
  chapters:
    - index.qmd
    - pages/1_intro.qmd

format:
  html:
    theme:
      - cosmo
      - brand



